pipeline {
    agent any

    environment {
        BUILD_SERVER_IP = '172.31.11.124'
    }

    stages {
        stage('Cleanup and Clone Repository') {
            steps {
                script {
                    // Remove existing Day6 directory and clone the latest repo
                    sh "ssh ubuntu@${BUILD_SERVER_IP} 'rm -rf /home/ubuntu/royal-challengers-glory && git clone https://github.com/adya1554/royal-challengers-glory.git /home/ubuntu/royal-challengers-glory'"
                }
            }
        }

        stage('Build Docker images on Build Server') {
            steps {
                script {
                    // Execute Ansible playbook on Build Server
                    sh "ssh ubuntu@${BUILD_SERVER_IP} 'ansible-playbook /home/ubuntu/royal-challengers-glory/ansible/docker-build.yml'"
                }
            }
        }

        stage('Deploy Script on Deploy Server') {
            steps {
                script {
                    // Execute deployment playbook on Deploy Server
                    sh "ssh ubuntu@${BUILD_SERVER_IP} 'ansible-playbook /home/ubuntu/royal-challengers-glory/ansible/k8s-script.yml'"
                }
            }
        }
    }
}
